platform :ios, ‘8.0’

target 'saasSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'SnapKit'
pod 'MJRefresh'

end
